################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
Crystalfontz128x128_ST7735.obj: /Users/Doanh/Documents/ECE_3849/final_project/libraries/display/Crystalfontz128x128_ST7735.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran" --include_path="/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/buttonsDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/display" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/elapsedTime" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/joystickDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/pll" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/timerLib" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/HAL_TM4C1294" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/driverlib" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/utils" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/portable/CCS/ARM_CM4F" --include_path="PROJECT_LOC" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HAL_EK_TM4C1294XL_Crystalfontz128x128_ST7735.obj: /Users/Doanh/Documents/ECE_3849/final_project/libraries/display/HAL_EK_TM4C1294XL_Crystalfontz128x128_ST7735.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran" --include_path="/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/buttonsDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/display" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/elapsedTime" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/joystickDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/pll" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/timerLib" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/HAL_TM4C1294" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/driverlib" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/utils" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/portable/CCS/ARM_CM4F" --include_path="PROJECT_LOC" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

button.obj: /Users/Doanh/Documents/ECE_3849/final_project/libraries/buttonsDriver/button.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran" --include_path="/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/buttonsDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/display" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/elapsedTime" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/joystickDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/pll" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/timerLib" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/HAL_TM4C1294" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/driverlib" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/utils" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/portable/CCS/ARM_CM4F" --include_path="PROJECT_LOC" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

controller_logic.obj: /Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran/controller_logic.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran" --include_path="/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/buttonsDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/display" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/elapsedTime" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/joystickDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/pll" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/timerLib" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/HAL_TM4C1294" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/driverlib" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/utils" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/portable/CCS/ARM_CM4F" --include_path="PROJECT_LOC" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

debug_uart.obj: /Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran/debug_uart.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran" --include_path="/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/buttonsDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/display" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/elapsedTime" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/joystickDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/pll" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/timerLib" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/HAL_TM4C1294" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/driverlib" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/utils" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/portable/CCS/ARM_CM4F" --include_path="PROJECT_LOC" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

%.obj: ../%.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran" --include_path="/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/buttonsDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/display" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/elapsedTime" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/joystickDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/pll" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/timerLib" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/HAL_TM4C1294" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/driverlib" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/utils" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/portable/CCS/ARM_CM4F" --include_path="PROJECT_LOC" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

motor.obj: /Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran/motor.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran" --include_path="/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/buttonsDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/display" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/elapsedTime" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/joystickDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/pll" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/timerLib" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/HAL_TM4C1294" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/driverlib" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/utils" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/portable/CCS/ARM_CM4F" --include_path="PROJECT_LOC" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

safety.obj: /Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran/safety.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran" --include_path="/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/buttonsDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/display" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/elapsedTime" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/joystickDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/pll" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/timerLib" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/HAL_TM4C1294" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/driverlib" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/utils" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/portable/CCS/ARM_CM4F" --include_path="PROJECT_LOC" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

sensor.obj: /Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran/sensor.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran" --include_path="/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/buttonsDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/display" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/elapsedTime" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/joystickDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/pll" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/timerLib" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/HAL_TM4C1294" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/driverlib" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/utils" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/portable/CCS/ARM_CM4F" --include_path="PROJECT_LOC" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

%.obj: ../%.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran" --include_path="/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/buttonsDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/display" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/elapsedTime" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/joystickDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/pll" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/timerLib" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/HAL_TM4C1294" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/driverlib" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/utils" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/portable/CCS/ARM_CM4F" --include_path="PROJECT_LOC" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

system_tasks.obj: /Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran/system_tasks.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran" --include_path="/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/buttonsDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/display" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/elapsedTime" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/joystickDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/pll" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/timerLib" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/HAL_TM4C1294" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/driverlib" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/utils" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/portable/CCS/ARM_CM4F" --include_path="PROJECT_LOC" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

timerLib.obj: /Users/Doanh/Documents/ECE_3849/final_project/libraries/timerLib/timerLib.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran" --include_path="/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/buttonsDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/display" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/elapsedTime" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/joystickDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/pll" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/timerLib" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/HAL_TM4C1294" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/driverlib" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/utils" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/portable/CCS/ARM_CM4F" --include_path="PROJECT_LOC" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

wireless.obj: /Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran/wireless.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/Doanh/Documents/ECE_3849/final_project/ece3849_finalProject_lphung_shtran" --include_path="/Applications/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/buttonsDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/display" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/elapsedTime" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/joystickDriver" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/pll" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/timerLib" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/libraries/HAL_TM4C1294" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/driverlib" --include_path="/Users/Doanh/ti/TivaWare_C_Series-2.2.0.295/utils" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/include" --include_path="/Users/Doanh/Documents/ECE_3849/final_project/FreeRTOS/portable/CCS/ARM_CM4F" --include_path="PROJECT_LOC" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


